### ISSUE TITLE
背景透明度变化可以加个动画吗

### ISSUE THREAD

**Issue by wyt666** [SPStore/SPAlertController#10]
加个动画，显得更柔和一些，现在透明度变化的太生硬
![6c63dbd6-59ec-4594-b857-540ebad1b9f1](https://user-images.githubusercontent.com/15173846/50586390-2b028b80-0eb4-11e9-8a23-8a1e6a8f7f0f.png)

**Comment by SPStore** [comment]
你观察的好仔细啊，我仔细看了看，好像是有些生硬，这是因为我作背景alpha从0~1变化的动画加了个主线程，现在已经改好了

**Comment by wyt666** [comment]
好的，细节还是很重要的🧐
