### ISSUE TITLE
黑色透明背景下弹出键盘渲染有问题

### ISSUE THREAD

**Issue by enefry** [SPStore/SPAlertController#2]
没有更新背景中的对话框大小.导致背景出现一块透明内容

必现

重现方式:
1. 设置一个 textfield 作为 centerview
2. 弹出对话框
3.选中 textfield. 
4. 弹出键盘

**Comment by SPStore** [comment]
很快会有新版本，这次优化了非常多的内容，你说的问题不会再有了
